services:
  - type: worker
    name: render-subnet-router
    env: docker
    autoDeploy: false
    envVars:
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: TAILSCALE_SERVE
        value: 3000
    disk:
      name: tailscale-state
      mountPath: /var/lib/tailscale
      sizeGB: 1

